export default [
  {
    title: "MMA lawyer website",
    logo: {
      logoSrc: "/mma-logo.png",
      logoW: 128,
      logoH: 128,
    },
    imgSrc: "/mma-art-3.png",
    content:
      "A website that provide potential clients with information about the lawyer's services and to facilitate easy contact. It serves as a professional online presence to attract and inform prospective clients.",
    link: "/case-studies/mma",
    gradientBgColor: "linear-gradient(to bottom, #EAABCA 0%, #E788B0 100%)",
    boxShadow: "rgb(177 100 132 / 65%) 0px 5px 10px",
    isReversed: false,
    cardImgAsset: {
      src: "/featured-project-art-1.png",
      w: 198,
      h: 229,
      alt: "rocket-img",
      top: "-100px",
      left: "-80px",
      animation: "animate__slide_in_bl",
      isGlitched: false,
    },
  },
  {
    title: "The World’s Best Selling Tool For The Home Service Industry",
    logo: {
      logoSrc: "/rb-logo.png",
      logoW: 356,
      logoH: 50,
    },
    imgSrc: "/mma-art-3.png",
    content:
      "A software tool designed to help service-based businesses manage and automate their bidding and sales processes. It provides a range of features aimed at streamlining the workflow from initial customer contact to closing a sale.",
    link: "/case-studies/mma",
    gradientBgColor: "linear-gradient(to bottom, #0094FF 0%, #002BC5 100%)",
    boxShadow: "rgb(42 44 203 / 65%) 0px 5px 10px",
    isReversed: true,
    cardImgAsset: {
      src: "/featured-project-art-2.png",
      w: 209,
      h: 152,
      alt: "cat-img",
      top: "-150px",
      left: "20px",
      animation: "animate__slide_in_skew",
      isGlitched: false,
    },
  },
  {
    title: "MMA lawyer website",
    logo: {
      logoSrc: "/mma-logo.png",
      logoW: 128,
      logoH: 128,
    },
    imgSrc: "/mma-art-3.png",
    content:
      "A website that provide potential clients with information about the lawyer's services and to facilitate easy contact. It serves as a professional online presence to attract and inform prospective clients.",
    link: "/case-studies/mma",
    gradientBgColor: "linear-gradient(to bottom, #F0FDA4 0%, #DEE20B 100%)",
    boxShadow: "rgb(223 207 60 / 65%) 0px 5px 10px",
    isReversed: false,
    cardImgAsset: {
      src: "/featured-project-art-3.png",
      w: 300,
      h: 278,
      alt: "person-on-phone-img",
      top: "-240px",
      left: "20px",
      animation: "glitch-in",
      isGlitched: true,
      glitchedImages: [
        "/featured-project-art-3-glitched-1.png",
        "/featured-project-art-3-glitched-2.png",
        "/featured-project-art-3-glitched-3.png",
      ],
    },
  },
];
